// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package schema

import (
	"database/sql"
	"time"
)

type AppRegisteredUser struct {
	WcaID        string
	StateID      string
	RegisterDate time.Time
}

type AppState struct {
	StateID   string
	StateName string
}

type DatalakeAllPersonsWithState struct {
	WcaID   string
	StateID string
}

type DatalakeCompetition struct {
	CompetitionID string
	StateID       string
}

type DatalakeCompetitionsByPersonAndState struct {
	WcaID         string
	StateID       string
	NCompetitions int32
}

type DatalakeCompetitor struct {
	WcaID   string
	WcaName string
}

type DatalakeEstimatedStateForUser struct {
	WcaID   string
	StateID string
}

type DatalakeExportDate struct {
	LastUpdate sql.NullTime
}

type DatalakeRankingAverage struct {
	WcaID   string
	StateID string
	EventID string
	Average sql.NullInt32
	Ranking int32
}

type DatalakeRankingSingle struct {
	WcaID   string
	StateID string
	EventID string
	Single  sql.NullInt32
	Ranking int32
}

type DatalakeRankingSum struct {
	WcaID          string
	StateID        string
	RankingSingle  int32
	RankingAverage int32
}

type DatalakeSumOfRank struct {
	WcaID      string
	SumSingle  sql.NullInt32
	SumAverage sql.NullInt32
	SumSum     sql.NullInt32
}

type DumpCompetition struct {
	ID   string
	Name string
}

type DumpCompetitionsByPersonAndCountry struct {
	WcaID         string
	CountryName   string
	NCompetitions sql.NullInt32
}

type DumpResult struct {
	Personid      string
	Eventid       string
	Competitionid string
	Value1        sql.NullInt32
	Value2        sql.NullInt32
	Value3        sql.NullInt32
	Value4        sql.NullInt32
	Value5        sql.NullInt32
	Best          sql.NullInt32
}

type DumpResultsByState struct {
	WcaID   string
	StateID string
	EventID string
	Average sql.NullInt32
	Single  sql.NullInt32
}
